export const ListaMeo = [
    { channel: 1, name: "RTP 1" },
    { channel: 2, name: "RTP 2" },
    { channel: 3, name: "SIC" },
    { channel: 4, name: "TVI" },
    { channel: 5, name: "SIC Notícias" },
    { channel: 6, name: "RTP 3" },
    { channel: 7, name: "CNN Portugal" },
    { channel: 8, name: "CMTV" },
    { channel: 9, name: "SIC Mulher" },
    { channel: 10, name: "Globo" },
    { channel: 11, name: "11" },
    { channel: 12, name: "TVI Ficção" },
    { channel: 13, name: "A Bola TV" },
    { channel: 14, name: "Sport TV+" },
    { channel: 15, name: "Porto Canal" },
    { channel: 17, name: "Veja" },
    { channel: 37, name: "Sporting TV" },
    { channel: 38, name: "Eurosport 1" },
    { channel: 40, name: "Disney Channel" },
    { channel: 41, name: "Cartoon Network" },
    { channel: 42, name: "Biggs" },
    { channel: 43, name: "SIC K" },
    { channel: 44, name: "Nickelodeon" },
    { channel: 45, name: "Disney Junior" },
    { channel: 46, name: "Panda" },
    { channel: 47, name: "Boomerang" },
    { channel: 48, name: "Jim Jam" },
    { channel: 49, name: "Baby TV" },
    { channel: 50, name: "Lolly Kids" },
    { channel: 92, name: "Odisseia" },
    { channel: 95, name: "National Geographic Channel" },
  ];

export const Apps = [
    { name: 'Telepizza', link: 'https://yubuy.app.iptv.telecom.pt:443/YubuyUserAz/sendData.aspx?SourceChannel=MAPP&partnerName=telepizza&account=$(acct)&deviceid=$(dev)' },
    { name: 'Pizzahut', link: 'https://yubuy.app.iptv.telecom.pt:443/YubuyUserAz/sendData.aspx?SourceChannel=MAPP&partnerName=pizhm&account=$(acct)&deviceid=$(dev)' },
    { name: 'NoMenu', link: 'https://yubuy.app.iptv.telecom.pt:443/YubuyUserAz/sendData.aspx?SourceChannel=MAPP&partnerName=nomenu&account=$(acct)&deviceid=$(dev)' },
    { name: 'Benfica', link: 'https://yubuy.app.iptv.telecom.pt:443/YubuyUserAz/sendData.aspx?SourceChannel=MAPP&partnerName=benfica&account=$(acct)&deviceid=$(dev)' }
]