export const ListaMeo = [
    { channel: 1, name: "RTP 1" },
    { channel: 2, name: "RTP 2" },
    { channel: 3, name: "SIC" },
    { channel: 4, name: "TVI" },
    { channel: 5, name: "SIC Notícias" },
    { channel: 6, name: "RTP 3" },
    { channel: 7, name: "CNN Portugal" },
    { channel: 8, name: "CMTV" },
    { channel: 9, name: "SIC Mulher" },
    { channel: 10, name: "Globo" },
    { channel: 11, name: "11" },
    { channel: 12, name: "TVI Ficção" },
    { channel: 13, name: "A Bola TV" },
    { channel: 14, name: "Sport TV+" },
    { channel: 15, name: "Porto Canal" },
    { channel: 17, name: "Veja" },
    { channel: 21, name: "SportTV1" },
    { channel: 22, name: "SportTV2" },
    { channel: 23, name: "SportTV3" },
    { channel: 24, name: "SportTV4" },
    { channel: 25, name: "SportTV5" },
    { channel: 26, name: "SportTV6" },
    { channel: 31, name: "Eleven 1" },
    { channel: 32, name: "Eleven 2" },
    { channel: 33, name: "Eleven 3" },
    { channel: 34, name: "Eleven 4" },
    { channel: 35, name: "Eleven 5" },
    { channel: 36, name: "Eleven 6" },
    { channel: 37, name: "Sporting TV" },
    { channel: 38, name: "Eurosport 1" },
    { channel: 40, name: "Disney Channel" },
    { channel: 41, name: "Cartoon Network" },
    { channel: 42, name: "Biggs" },
    { channel: 43, name: "SIC K" },
    { channel: 44, name: "Nickelodeon" },
    { channel: 45, name: "Disney Junior" },
    { channel: 46, name: "Panda" },
    { channel: 47, name: "Boomerang" },
    { channel: 48, name: "Jim Jam" },
    { channel: 49, name: "Baby TV" },
    { channel: 50, name: "Lolly Kids" },
    { channel: 70, name: "FOX" },
    { channel: 72, name: "FOX Crime" },
    { channel: 74, name: "AXN" },
    { channel: 92, name: "Odisseia" },
    { channel: 95, name: "National Geographic Channel" },
    { channel: 160, name: "RTP Açores" },
  ];

export const Apps = [
    { name: 'Telepizza', link: 'https://yubuy.app.iptv.telecom.pt:443/YubuyUserAz/sendData.aspx?SourceChannel=MAPP&partnerName=telepizza&account=$(acct)&deviceid=$(dev)' },
    { name: 'Pizzahut', link: 'https://yubuy.app.iptv.telecom.pt:443/YubuyUserAz/sendData.aspx?SourceChannel=MAPP&partnerName=pizhm&account=$(acct)&deviceid=$(dev)' },
    { name: 'NoMenu', link: 'https://yubuy.app.iptv.telecom.pt:443/YubuyUserAz/sendData.aspx?SourceChannel=MAPP&partnerName=nomenu&account=$(acct)&deviceid=$(dev)' },
    { name: 'Benfica', link: 'https://yubuy.app.iptv.telecom.pt:443/YubuyUserAz/sendData.aspx?SourceChannel=MAPP&partnerName=benfica&account=$(acct)&deviceid=$(dev)' }
]